import Vue from "vue";

import Vuetify, {
  VApp,
  VBadge,
  VBtn,
  VCard,
  VCardActions,
  VCardText,
  VContent,
  VContainer,
  VDivider,
  VFlex,
  VIcon,
  VLayout,
  VList,
  VListTile,
  VListTileAction,
  VListTileAvatar,
  VListTileContent,
  VListTileSubTitle,
  VListTileTitle,
  VNavigationDrawer,
  VSnackbar,
  VStepper,
  VStepperStep,
  VStepperContent,
  VTextField,
  VToolbar,
  VToolbarSideIcon,
  VToolbarTitle
} from "vuetify/lib";
import "vuetify/src/stylus/app.styl";

Vue.use(Vuetify, {
  components: {
    VApp,
    VBadge,
    VBtn,
    VCard,
    VCardActions,
    VCardText,
    VContent,
    VContainer,
    VDivider,
    VFlex,
    VIcon,
    VLayout,
    VList,
    VListTile,
    VListTileAction,
    VListTileAvatar,
    VListTileContent,
    VListTileSubTitle,
    VListTileTitle,
    VNavigationDrawer,
    VSnackbar,
    VStepper,
    VStepperStep,
    VStepperContent,
    VTextField,
    VToolbar,
    VToolbarSideIcon,
    VToolbarTitle
  }
});
